kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: netbox-migration
  label:
    app: netbox-migration
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'netbox-migration:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Dockerfile
    dockerfile: |
      FROM ubuntu
      RUN apt update \
          && apt install -y openssh-client \
          && rm -rf /var/lib/apt/lists/* \
          && apt clean
  runPolicy: Serial
  triggers:
    - type: ConfigChange
