apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Release.Namespace }}-job'
  namespace: adrien-test
 labels:
    app: '{{ .Release.Namespace }}-netbox-migration'
    housekeeping: {{ include "migration.housekeeping" . | quote}}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
spec:
  selector: {}
  template:
    metadata:
      name: pi
    spec:
      serviceAccountName: '{{ .Release.Namespace }}-serviceaccount'
      restartPolicy: OnFailure
      containers:
        - name: fetch-data
          image: image-registry.openshift-image-registry.svc:5000/netbox-migration/netbox-migration:latest
          imagePullPolicy: Always
          command:
            - 'bin/sh'
            - '-c'
            - '/migration/configmap/entrypoint.sh'
          volumeMounts:
            - name: migration-data
              mountPath: "/migration/data/"
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: migration-data
          persistentVolumeClaim:
            claimName: netbox-migration