apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name | trunc 63 | trimSuffix "-"}}-netbox-migration
  labels:
    app: netbox-migration
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: fetch-data
      image: image-registry.openshift-image-registry.svc:5000/netbox-migration/netbox-migration:latest
      imagePullPolicy: Always
      command:
        - 'bin/sh'
        - '-c'
        - '/migration/configmap/entrypoint.sh'
      volumeMounts:
        - name: migration-data
          mountPath: "/migration/data/"
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
  volumes:
    - name: migration-data
      persistentVolumeClaim:
        claimName: netbox-migration
        defaultMode: 0644