apiVersion: v1
kind: Pod
metadata:
  name: netbox-migration
  labels:
    app: netbox-migration
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: fetch-data
      image: image-registry.openshift-image-registry.svc:5000/test2/netbox-migration-imagestream:latest
      imagePullPolicy: Always
      command:
        - 'bin/sh'
        - '-c'
        - '/migration/configmap/entrypoint.sh'
      volumeMounts:
        - name: migration-secret
          mountPath: "/migration/secret/"
        - name: migration-configmap
          mountPath: "/migration/configmap/"
        - name: migration-data
          mountPath: "/migration/data/"
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
  volumes:
    - name: migration-secret
      secret:
        secretName: netbox-migration
        defaultMode: 0600
    - name: migration-configmap
      configMap:
        name: netbox-migration
        defaultMode: 0710
    - name: migration-data
      persistentVolumeClaim:
        claimName: netbox-migration
        defaultMode: 0644