kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ .Release.Namespace }}-image-puller'
  namespace: netbox-migration
  labels:
    app: netbox-migration
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: ServiceAccount
    name: netbox-migration
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:image-puller"
