apiVersion: v1
kind: ServiceAccount
metadata:
  name: netbox-migration
  labels:
    app: netbox-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation